services:
  mysqldb:
    image: mysql:8.0
    volumes:
      - db-test-nodejs:/var/lib/mysql
    # env_file: ./.env
    environment:
      # - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      # - MYSQL_DATABASE=$DB_DATABASE_NAME
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test_nodejs
    ports:
      # MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      - "3307:3306"
  app:
    # depends_on:
    #   - mysqldb
    build:
      context: ./
      dockerfile: Dockerfile
    # restart: always
    # env_file: ./.env
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_DB: test_nodejs

volumes:
  db-test-nodejs:
