services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $PORT:$NODE_LOCAL_PORT
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: $DB_HOSTNAME_DOCKER
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DB: $DB_DATABASE_NAME

  mysqldb:
    image: mysql:8.0
    env_file: ./.env
    volumes:
      - db-test-nodejs:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE_NAME
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

volumes:
  db-test-nodejs:
