version: '3.8'
services:
  app:
    build: ./
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$PORT
    environment:
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE_NAME
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

